/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package leiloestdsat;

import javax.swing.JOptionPane;

/**
 *
 * @author Sufleh
 */
public class cadastro extends javax.swing.JFrame {

    /**
     * Creates new form cadastro
     */
    public cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SISTEMATEXT = new javax.swing.JLabel();
        CADASTRETEXT = new javax.swing.JLabel();
        NOMETEXTFIELD = new javax.swing.JLabel();
        nometextfield = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        valortextfield = new javax.swing.JTextField();
        cadastrarbutton = new javax.swing.JButton();
        consultarbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SISTEMATEXT.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        SISTEMATEXT.setText("SISTEMA DELEILÕES");

        CADASTRETEXT.setText("CADASTRE UM NOVO PRODUTO");

        NOMETEXTFIELD.setText("NOME:");

        jLabel1.setText("VALOR:");

        valortextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valortextfieldActionPerformed(evt);
            }
        });

        cadastrarbutton.setText("cadastrar");
        cadastrarbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarbuttonActionPerformed(evt);
            }
        });

        consultarbutton.setText("consultar produtos");
        consultarbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(SISTEMATEXT))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(CADASTRETEXT))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(valortextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NOMETEXTFIELD)
                                .addGap(18, 18, 18)
                                .addComponent(nometextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(cadastrarbutton)))
                .addContainerGap(101, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(consultarbutton)
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(SISTEMATEXT)
                .addGap(27, 27, 27)
                .addComponent(CADASTRETEXT)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NOMETEXTFIELD)
                    .addComponent(nometextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(valortextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(cadastrarbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(consultarbutton)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void valortextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valortextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valortextfieldActionPerformed

    private void consultarbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarbuttonActionPerformed
        // TODO add your handling code here:
        listagem lis = new listagem();
        lis.setVisible(true);
        
    }//GEN-LAST:event_consultarbuttonActionPerformed

    private void cadastrarbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarbuttonActionPerformed
        // TODO add your handling code here:
        
        produtos po = new produtos();
        produtosDAO pro = new produtosDAO();
        
          boolean status;
            int resposta;
            
            po.setNome(nometextfield.getText());
            po.setValor(Integer.parseInt(valortextfield.getText()));
            po.setStatus("a venda");
            
            pro = new produtosDAO();
            
            status = pro.conectar();
            
            if (status == false)
       {
            JOptionPane.showMessageDialog(null,"Erro de conexão");
       }
            else
       {
           resposta = pro.salvar(po);
           if(resposta== 1)
           {
               JOptionPane.showMessageDialog(null,"produto cadastrado com sucesso ");
               
            }
          
           else 
           {
               JOptionPane.showMessageDialog(null,"Erro ao tentar cadastrar produto ");
           }
           pro.desconectar();
       }
    }//GEN-LAST:event_cadastrarbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CADASTRETEXT;
    private javax.swing.JLabel NOMETEXTFIELD;
    private javax.swing.JLabel SISTEMATEXT;
    private javax.swing.JButton cadastrarbutton;
    private javax.swing.JButton consultarbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nometextfield;
    private javax.swing.JTextField valortextfield;
    // End of variables declaration//GEN-END:variables
}
